package br.com.fiap.medix.chat;

public enum ChatStep {
    INICIO,

    AGENDAMENTO_AGUARDANDO_EMAIL,
    AGENDAMENTO_AGUARDANDO_ESPECIALIDADE,
    AGENDAMENTO_ESCOLHENDO_MEDICO,
    AGENDAMENTO_AGUARDANDO_DATA,
    AGENDAMENTO_ESCOLHENDO_HORARIO,
    AGENDAMENTO_ESCOLHENDO_UNIDADE,
    AGENDAMENTO_CONFIRMACAO,

    LISTAGEM_AGUARDANDO_EMAIL,

    CANCELAMENTO_AGUARDANDO_EMAIL,
    CANCELAMENTO_ESCOLHENDO_AGENDAMENTO,
    CANCELAMENTO_CONFIRMACAO
}